- name: Install zsh
  lineinfile:
    backup: yes
    dest: /etc/shells
    regexp: ^/bin/zsh
    line: /bin/zsh
  become: true

- name: Setup oh-my-zsh
  block: 
  - name: Verify if oh-my-zsh Is Installed
    stat:
      path: "~/.oh-my-zsh/"
    register: "ohmyzsh_installed"

  - name: Install oh-my-zsh
    shell: bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    when: not ohmyzsh_installed.stat.exists

  - name: Install additional oh-my-zsh packages
    block:
    - name: "[dotfiles] download configs"
      git:  
        repo: "{{ item.name | default(item) }}"
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.dest }}"
        update: yes
        clone: yes
      loop: 
        - { name: "https://github.com/zsh-users/zsh-autosuggestions", dest: "zsh-autosuggestions" }
        - { name: "https://github.com/zsh-users/zsh-completions", dest: "zsh-completions" }
        
  - name: Default to zsh
    user:
      name: "{{ ansible_env.USER }}"
      shell: /bin/zsh
    become: true

- name: dotfiles folder
  block:
  - name: "[dotfiles] exists"
    stat: 
      path: "{{ ansible_env.HOME }}/dotfiles"
    register: dotfiles_exists
  - name: "[dotfiles] download configs"
    git:  
      repo: "git@github.com:kubamarchwicki/dotfiles.git"
      dest: "{{ ansible_env.HOME }}/dotfiles"
      update: yes
      clone: yes
    when: not dotfiles_exists.stat.exists
  - name: "[dotfiles] links"
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
      force: yes
    loop:
      - { src: "~/dotfiles/git/gitconfig", dest: "~/.gitconfig"}
      - { src: "~/dotfiles/git/gitignore_global", dest: "~/.gitignore_global"}
      - { src: "~/dotfiles/zsh/zshrc_aliases", dest: "~/.zshrc_aliases"}
      - { src: "~/dotfiles/zsh/zshrc_helpers", dest: "~/.zshrc_helpers"}
      - { src: "~/dotfiles/zsh/docker_aliases", dest: "~/.docker_aliases"}
      - { src: "~/dotfiles/zsh/zshrc", dest: "~/.zshrc"}
      - { src: "~/dotfiles/macos/yabai", dest: "~/.config/yabai"}
      - { src: "~/dotfiles/macos/skhd", dest: "~/.config/skhd"}
      - { src: "~/dotfiles/macos/karabiner", dest: "~/.config/karabiner"}