- name: Installing MacOS-I3 Packages
  block:
    - name: Tap koekeishiya/formulae
      homebrew_tap:
        name: koekeishiya/formulae
        state: present
    - name: Install packages
      homebrew:
        name: "{{ item.name | default(item) }}"
        state: present
      loop: 
        - koekeishiya/formulae/yabai
        - koekeishiya/formulae/skhd
    - name: Configure yabai
      command: |
        echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee -a /private/etc/sudoers.d/yabai
    - name: Start yabai services
      command: yabai --start-service
    - name: Start skhd 
      command: skhd --start-service

- name: Install mac tools
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: present
  loop:
    - dockutil
    - m-cli
    - mas

- name: Install AppStore applications
  shell: "mas install {{ item.id }}"
  with_items:
    - { id: 409201541, name: "Pages" }
    - { id: 409203825, name: "Numbers" }

- name: Remove Unused Dock Items
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items: 
    - Launchpad
    - Safari
    - Mail
    - Contacts
    - Calendar
    - Freeform
    - TV
    - Music
    - Notes
    - Reminders
    - Maps
    - Photos
    - FaceTime
    - iBooks
    - App Store

- name: Set Global Settings
  osx_defaults: domain=NSGlobalDomain key={{ item.key }} type={{ item.type }} value={{ item.value }}
  with_items:
    - { key: "NSAutomaticWindowAnimationsEnabled", type: "bool", value: "false" }
    - { key: "NSWindowResizeTime", type: "float", value: "0.0001" }
  notify:
    - Restart yabai

- name: Set Dock Settings
  osx_defaults: 
    domain: com.apple.dock
    key: "{{ item.key }}"
    type: "{{ item.type }}" 
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "orientation", type: "string", value: "bottom" }
    - { key: "autohide", type: "bool", value: "false" }
    - { key: "autohide-immutable", type: "bool", value: "true" }
    - { key: "show-recents", type: "bool", value: "false" }
    - { key: "tilesize", type: "float", value: "32" }
    - { key: "largesize", type: "float", value: "48" }
  notify:
    - Kill Dock

- name: Set Finder Settings
  osx_defaults: 
    domain: com.apple.finder
    key: "{{ item.key }}" 
    type: "{{ item.type }}" 
    value: "{{ item.value }}"
    state: present
  with_items:
    - { key: "ShowStatusBar", type: "bool", value: "true" }
    - { key: "ShowPathbar", type: "bool", value: "true" }
    - { key: "QLEnableTextSelection", type: "bool", value: "true" }
    - { key: "_FXShowPosixPathInTitle", type: "bool", value: "true" }
    - { key: "FXDefaultSearchScope", type: "string", value: "SCcf" }
    - { key: "FXEnableExtensionChangeWarning", type: "bool", value: "false" }
    - { key: "OpenWindowForNewRemovableDisk", type: "bool", value: "true" }
    - { key: "FXPreferredViewStyle", type: "string", value: "Nlsv" }
    - { key: "WarnOnEmptyTrash", type: "bool", value: "false" }
    - { key: "ShowHardDrivesOnDesktop", type: "bool", value: "false" }
  notify:
    - Kill Finder

- name: Verify if iTerm Runs at Login
  command: osascript -e 'tell application "System Events" to get the name of every login item'
  register: login_items
  changed_when: false

- name: Run iTerm At Login
  command: osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/iTerm.app", hidden:true}'
  when: "'iTerm' not in login_items.stdout"
  ignore_errors: true
