- name: Updating Homebrew
  homebrew:
    update_homebrew: true

- name: Installing Homebrew Packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: present
  loop: 
    - curl
    - wget
    - bat
    - youtube-dl

- name: Setup password-store
  block:
  - name: "[pass] install pass package"
    homebrew:
      name: "{{ item.name | default(item) }}"
      state: present
    loop:
      - pass
      - pinentry-mac #prompts you for your passphrase
  - name: "[pass] passff-host for firefox"
    shell: curl -sSL github.com/passff/passff-host/releases/latest/download/install_host_app.sh | bash -s -- firefox    
  - name: "[pass] gnupg agent setup"
    copy:
      dest: "~/.gnupg/gpg-agent.conf"
      content: |
        pinentry-program /opt/homebrew/bin/pinentry-mac

- name: Refreshing sudo Cache
  command: "echo none"
  changed_when: false
  become: true

- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: present
    options: "{{ item.install_options | default(omit) }}"
    accept_external_apps: yes
  ignore_errors: true
  loop: 
    - slack    
    - firefox
    - simplenote
    - gimp
    - signal
    - dropbox
  notify:
    - brew doctor

- name: Install fonts
  import_tasks: fonts-setup.yml

- name: Setup mac properties
  import_tasks: macos-setup.yml
